### ISSUE TITLE
sometimes cannot properly verify password.

### ISSUE THREAD

**Issue by evan0greenup** [sudo-project/sudo#114] opened 2021-09-21 05:35 UTC
Version: 1.9.8.p1

Problem: 

Sometimes cannot properly verify the password. After type correct password, it said that the password is incorrect and let user retype.

After logout and login again, the problem disappeared.

**Comment by millert** [comment] 2022-01-11 20:48
This sounds like a PAM problem of some kind.  If this happens again, check the logs for PAM errors and check to see if other programs (like su for instance) are able to verify your password.

**Comment by millert** [comment] 2022-04-01 19:42
Closing; unable to reproduce and sounds like a PAM issue.  Without more information there's nothing I can do.

**Closed by millert** 2022-04-01 19:42 UTC
