### ISSUE TITLE
in container: sudo: setrlimit(RLIMIT_CORE): Operation not permitted

### ISSUE THREAD

**Issue by juhp** [sudo-project/sudo#42] opened 2020-03-14 04:58 UTC
Apparently [since version 1.8.29](https://gitlab.alpinelinux.org/alpine/aports/issues/11122), sudo [started outputting](https://bugzilla.redhat.com/show_bug.cgi?id=1773148) this warning in Linux rootless containers:

```
$ sudo hello > /dev/null
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
```
which is quite annoying. This is with sudo-1.9.0b1.
(There are quite [a lot of reports](https://www.google.com/search?q=sudo%3A+setrlimit%28RLIMIT_CORE%29%3A+Operation+not+permitted) of this.)

Can something be done to alleviate it?

**Comment by millert** [comment] 2020-03-14 16:03
Handling of RLIMIT_CORE appears to be buggy in Linux containers.  When sudo tries to restore the original coredump limit (which appears to be RLIM_INFINITY) as uid 0 it gets EPERM, which should not happen.  Sudo 1.8.28 just silently ignored the failure, in 1.8.29 and above a warning is written to the standard error.  I'll probably just go back to ignoring the failure but this is not actually a bug in sudo.

**Comment by millert** [comment] 2020-03-14 17:34
This is fixed by 712afe03195e9747a442cac633b03dc5c8bfa54c

**Comment by millert** [comment] 2020-03-14 22:27
Fixed in sudo 1.8.31p1, available now.

**Closed by millert** 2020-03-14 22:27 UTC

**Comment by juhp** [comment] 2020-03-15 04:49
Thanks so much!!

**Comment by juhp** [comment] 2020-03-21 15:30
BTW do you plan to add this also to 1.9.0?

**Comment by millert** [comment] 2020-03-21 15:31
Yes, it was already committed to what will be the 1.9 tree

**Comment by juhp** [comment] 2020-03-22 13:18
Great, thank you for confirming

**Comment by vorburger** [comment] 2020-04-04 19:46
FTR in the `sudo` 1.9.x (?) included today in Fedora 30 this wasn't included, yet; but FYI to anyone hitting this, as per https://bugzilla.redhat.com/show_bug.cgi?id=1773148 (and https://ask.fedoraproject.org/t/sudo-setrlimit-rlimit-core-operation-not-permitted/4223) there is a simple workaround:

    echo "Set disable_coredump false" >> /etc/sudo.conf

I've used this in https://github.com/vorburger/cloudshell.

**Comment by juhp** [comment] 2020-04-07 15:12
> FTR in the `sudo` 1.9.x (?) included today in Fedora 30 this wasn't included, yet

It _is_ fixed in `sudo-1.8.31p1-1.fc30` in Fedora update-testing for me - anyway better to report downstream problems to bugzilla. :)

**Comment by uwe72** [comment] 2020-04-27 09:47
I am new to linux. sorry to tell, but how can this be possible in a new installed linux, up-to-date

**Comment by ChameleonDevil** [comment] 2020-07-16 08:39
I have just installed `sudo` inside a Docker container - `apt-get update && apt-get install -y sudo` and this notification is still in the Docker Ubuntu 20.04 container.

The only thing that work was was this user said above:

> FTR in the `sudo` 1.9.x (?) included today in Fedora 30 this wasn't included, yet; but FYI to anyone hitting this, as per https://bugzilla.redhat.com/show_bug.cgi?id=1773148 (and https://ask.fedoraproject.org/t/sudo-setrlimit-rlimit-core-operation-not-permitted/4223) there is a simple workaround:
> 
> ```
> echo "Set disable_coredump false" >> /etc/sudo.conf
> ```
> 
> I've used this in https://github.com/vorburger/cloudshell.

Creating a new `/etc/sudo.conf` file and restarting the container and testing in shell again; those information messages are not showing anymore.

**Comment by warpspin** [comment] 2020-10-28 13:37
> Handling of RLIMIT_CORE appears to be buggy in Linux containers. When sudo tries to restore the original coredump limit (which appears to be RLIM_INFINITY) as uid 0 it gets EPERM, which should not happen.

Raising a hard limit without CAP_SYS_RESOURCE causes EPERM. This is not a bug in the containers in my opinion. The proper solution would probably be that sudo only sets the soft limit to 0 and leaves the hard limit untouched.

This would also solve the even more annoying than the warning problem, where sudo in a rootless container permanently messes up the coredump hard limit for processes it launches without giving any indication it did so.

**Comment by govindsajgane** [comment] 2022-08-10 10:59
can we make these changes echo "Set disable_coredump false" >> /etc/sudo.conf without rebooting. just to avoid/disturb other people using the same machine?

**Comment by millert** [comment] 2022-08-10 13:14
Yes, there is no need to reboot.  The sudo.conf file is read every time sudo is run.

**Comment by govindsajgane** [comment] 2022-08-10 16:41
I tried it and it worked. But it worked only once. After that if im trying to change nofile limit using c programm which uses settlimit look like doest work. Setting disable_core false means no core genration? Like core file generation on segmentatiom fault?

**Comment by govindsajgane** [comment] 2022-08-10 16:43
@millert thank you for your help. Is it correct way to set nofile limit while running process ?? If yes it wont allow without set disble coredump  to false.

**Comment by douglasg14b** [comment] 2023-04-23 01:24
I'm on sudo v 1.9.9 and this still appears to be a problem? I keep being directed to this github thread as the solution to being unable to mount an NFS volume in portainer on a linux container 🤔

**Comment by velkrosmaak** [comment] 2023-09-15 22:45
> I'm on sudo v 1.9.9 and this still appears to be a problem? I keep being directed to this github thread as the solution to being unable to mount an NFS volume in portainer on a linux container 🤔

exactly the same issue here! trying to mount a share using fstab.

**Comment by erselbey** [comment] 2024-11-17 12:17
> Yes, there is no need to reboot. The sudo.conf file is read every time sudo is run.

No, you need to restart.
